#!/usr/bin/env bash
# Transfer a file from our client to a server
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	SSH_KEY=$4
	FILE=$1
	IP=$2
	USER=$3

	scp -i "$SSH_KEY" "$FILE" "$USER"@"$IP":~/.
fi
