#!/usr/bin/env bash
# Transfer a file from our client to a server
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]
then
	scp -o StrictHostKeyChecking=off "$1" "$3"@"$2":~/.
else
	scp -o StrictHostKeyChecking=off -i "$4" "$1" "$3"@"$2":~/.
fi
