#!/usr/bin/env bash
# Install HAproxy load balancer
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
# configure servers in HAproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.original.cfg
echo -e "# HAproxy for web servers" >> /etc/haproxy/haproxy.cfg
echo -e "frontend http-in" >> /etc/haproxy/haproxy.cfg
echo -e "\tbind *:80" >> /etc/haproxy/haproxy.cfg
echo -e "\tmode http" >> /etc/haproxy/haproxy.cfg
echo -e "\tdefault_backend servers" >> /etc/haproxy/haproxy.cfg

echo -e "\nbackend servers" >> /etc/haproxy/haproxy.cfg
echo -e "\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver 11178-web-01 18.206.92.141 check" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver 11178-web-02 44.192.79.41 check" >> /etc/haproxy/haproxy.cfg
