#!/usr/bin/env bash
# Install HAproxy load balancer
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
# configure servers in HAproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.original.cfg
{
	echo -e "# HAproxy for web servers"
	echo -e "frontend http-in"
	echo -e "\tbind *:80"
	echo -e "\tmode http"
	echo -e "\tdefault_backend servers"
	echo -e "\nbackend servers"
	echo -e "\tbalance roundrobin"
	echo -e "\tserver 11178-web-01 18.206.92.141:80 check"
	echo -e "\tserver 11178-web-02 44.192.79.41:80 check"
} >> /etc/haproxy/haproxy.cfg
service haproxy restart
