#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it
mysqldump --all-databases -uroot --password="$1" > backup.sql
tar -czf "$(date +%d-%m-%Y)".tar.gz backup.sql

