#!/usr/bin/env bash
# handles signals

# Display "I hate the kill command" when receiving a SIGTERM signal
trap 'echo "I hate the kill command"' TERM

# Display "Y U no love me?!" when receiving a SIGINT signal
trap 'echo "Y U no love me?!"' INT

# Deletes the file /var/run/myscript.pid and terminates
trap 'rm /var/run/myscript.pid; exit 0' QUIT TERM

echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done

