#!/usr/bin/env bash
# Print Best School 10 times using while loop
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"	# print Hi on the 9th iteration
	fi
	((i += 1))		# increments i. Same as i=$(( i + 1 ))
done

