#!/usr/bin/env bash
# Print Best School 10 times using while loop
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"		# print Hi on the 9th iteration
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i += 1))			# increments i. Same as i=$(( i + 1 ))
done

