#!/usr/bin/env bash
# Display the content of the current directory
FILE="school"
if [ -a $FILE ]
then
	echo "$FILE file exists"
	if [ -s $FILE ]
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi

	if [ -f $FILE ]
	then
		echo "$FILE is a regular file"
	fi
else
	echo "school file does not exist"
fi

