#!/bin/usr/env bash
# configures an Ubuntu server with the below requirements.
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2' ~/hosts.new
sed '/8.8.8.8*/8.8.8.8 facebook.com/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
